version: "3.8"

services:
  web:
    container_name: football-ai-predictor-web
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
